### ISSUE TITLE
Recommendation for browser testing

### ISSUE THREAD

**Issue by MDeane** [relevance/blue-ridge#10]
Do you store your dev apps on a network and access the fixtures directly from the network or do you configure web sharing to view files via ip address?

Any suggestions would be much appreciated.

**Comment by karnowski** [comment]
To run the Screw.Unit tests in-browser, I just use "rake js:fixtures" to open the fixtures directory in Finder (on Mac) or Firefox (on Linux) and then run the file locally through Firefox, Safari, or IE.
