### ISSUE TITLE
Make it work with ZenTest autotest

### ISSUE THREAD

**Issue by bartaz** [relevance/blue-ridge#16]
Blue-Ridge does a great job with testing JavaScript (even from command line) but it would be awesome if it would work with ZenTest's autotest, so the tests will automatically re-run when .js files will be edited.
Is it possible?

**Comment by jasonrudolph** [comment]
We don't have any immediate plans to add this feature, but I agree that this type of functionality would be nice to have.  

If/when we do add this kind of functionality, it's more likely that we'll add support for [beholder](http://github.com/spicycode/beholder).  We'd welcome a patch that provides ZenTest autotest support, but [we](http://thinkrelevance.com) use beholder, so it's unlikely that we'd build ZenTest autotest support for ourselves.

**Comment by drnic** [comment]
You could try using rstakeout to trigger "rake test:js TEST=..." if any files change

**Comment by drnic** [comment]
@jasonrudolph - what is your setup for beholder? Perhaps put this in a wiki page?

**Comment by jasonrudolph** [comment]
@drnic - We don't use beholder for Blue Ridge yet.  If/when we do use beholder with Blue Ridge, we'll be sure to add some docs so that others can do the same.

**Comment by bartaz** [comment]
@drnic - Thanks for a tip, I tried rstakeout and it works like a charm! I even got it giving me nice notifications when tests fail or pass.

**Comment by karnowski** [comment]
@drnic & @bartaz: could someone send me a quick write-up of how you're using rstakeout with BlueRidge?
