### ISSUE TITLE
Use of $ in test_runner.js a problem when using jQuery.noConfict()

### ISSUE THREAD

**Issue by aiwilliams** [relevance/blue-ridge#25]
See http://github.com/relevance/blue-ridge/blob/master/lib/test_runner.js#L39

That $.trim works better as window.jQuery.trim when I'm using prototype.js. Once I do, I get a different problem:

"test_runner.js", line 39: uncaught JavaScript runtime exception: TypeError: Cannot find function children in object Element #182 LI.

**Comment by aiwilliams** [comment]
As you likely know almost immediately, until all '$' references in that file are replaced with window.jQuery (or whatever), the runner does not work too with with prototype.js.

**Comment by karnowski** [comment]
Adam, thanks for catching this!  Fixed.
