### ISSUE TITLE
rake js:shell won't work without lib/env.rhino.js

### ISSUE THREAD

**Issue by aiwilliams** [relevance/blue-ridge#26]
It seems this file is missing in the repository. Is the documentation simply out of date? I get this when I run the rake task:

<pre><code>js: "<project>/vendor/plugins/blue-ridge/lib/shell.js", line 14: Couldn't read source file "<project>/vendor/plugins/blue-ridge/lib/env.rhino.js: <project>/vendor/plugins/blue-ridge/lib/env.rhino.js (No such file or directory)".
 - loaded env.js
js: "<project>/vendor/plugins/blue-ridge/lib/shell.js", line 17: uncaught JavaScript runtime exception: ReferenceError: "window" is not defined.
    at <project>/vendor/plugins/blue-ridge/lib/shell.js:17
    at <project>/vendor/plugins/blue-ridge/lib/shell.js:1</code></pre>

**Comment by karnowski** [comment]
Thanks for pointing this out, Adam!  I fixed this broken file path, which then made me find that the env-js.jar we were using was breaking the shell too.  I fixed this by updating to the env.js 1.0rc7.  Thanks!
