### ISSUE TITLE
ajax mocking

### ISSUE THREAD

**Issue by charleseff** [relevance/blue-ridge#27]
considering using rsim's fork which added this functionality:

http://github.com/rsim/blue-ridge/blob/b8fa6ce51a58a9fc4e5b02687749e820bda29d3b/lib/screw.mocking-ajax.js

**Comment by karnowski** [comment]
Thanks for the feedback.  Note that I've talked with rsim and suggested he submit his patch to Screw.Unit and/or Smoke.  Note that Blue Ridge vendors those toolkits as components, but we don't take patches directly to those component.  Thanks!
