### ISSUE TITLE
Clicking radio buttons does not seem to work

### ISSUE THREAD

**Issue by superchris** [relevance/blue-ridge#3]
I have a ScrewUnit test which interacts with a radio button and passes in browser but fails in blueridge.  It appears that clicking a radio button does not yet work in env.js.  I'm using jQuery("input.radio").click() to click it, if that matters.

**Comment by karnowski** [comment]
That sounds like a problem in env.js.  We'll see if we can get it fixed.

**Comment by karnowski** [comment]
env.js ticket: http://envjs.lighthouseapp.com/projects/21590-envjs/tickets/42-fail-176-core-check-first-radio-still-checked#ticket-42-2

**Comment by karnowski** [comment]
Chris, env.js has been updated and vastly improved.  Could you retest this and reopen the issue if it still doesn't work?  Thanks!
