### ISSUE TITLE
In browser runner

### ISSUE THREAD

**Issue by superchris** [relevance/blue-ridge#4]
Since I'm experiencing tests that fail in blueridge using rhino but pass in browser, I'm working on adding an in browser test runner using selenium rc.  The plan is to make running it as running it headless, eg. a rake task which starts selenium rc, runs test, shuts down selenium rc.  Is there any interest in this, or is this already being done by someone else?  I'll fork and check it in once I get it working.

**Comment by karnowski** [comment]
I think screw-unit-server does something similar to this.  I'd be interested in seeing the code, maybe making it optional Blue Ridge plugin that could be turned on/off via configuration.  To be honest, however, I'm more interested in making env.js better rather.

**Comment by karnowski** [comment]
Closing this ticket until we get a pull request.
