### ISSUE TITLE
Prototype.js Element#down doesn't work

### ISSUE THREAD

**Issue by aiwilliams** [relevance/blue-ridge#6]
With a simple html fixture, and a test like this:

```
it("has a problem with prototype?", function(){
  $('available').down('label').down('a');
  expect($('available').down('label')).to_not(be_undefined);
});
```

all is well when run in FF3. When running 'rake spec:javascripts':

```
Running people_chooser_spec.js with fixture 'fixtures/people_chooser.html'...

FAILED: PeopleChooser - has a problem with prototype?
          TypeError: Cannot find function down in object Element #22 DIV => available.
```

**Comment by karnowski** [comment]
env.js is having problems with Prototype.  I'll open this as a ticket in their Lighthouse.

**Comment by karnowski** [comment]
I opened the following env.js Lighthouse ticket to track this problem:
http://envjs.lighthouseapp.com/projects/21590-envjs/tickets/69-prototypes-down-method-is-unavailable

**Comment by karnowski** [comment]
Adam, env.js has been updated and greatly improved.  Could you please retest this and reopen if it's still an issue?  Thanks!

**Comment by aiwilliams** [comment]
Sure will! Thanks for the heads up.
