### ISSUE TITLE
$.print unavailable/incorrect

### ISSUE THREAD

**Issue by stuarthalloway** [relevance/blue-ridge#7]
The $.print function is alternately unavailable / underpowered. If you just add a call to $.print in the middle of a test, it fails (even though the jquery.print.js appears to have been included.)

If you call $.print from within a screw.matcher, it prints but not the value you would expect. For an array of ints I am seeing [{}] instead of [1,2,3]. This might be cause by smoke.core incorrectly trying to autodetect $.print availability

**Comment by karnowski** [comment]
I too am not seeing the $.print function in either command-line or in-browser tests.  It's missing when using Firebug's console too.  jQuery's internals are clearly using it, though, and Firebug shows the jquery.print.js is clearly loaded.  Not sure what's going on.

This may be related to issue #5 where JavaScript libraries seem to be loaded twice.

**Comment by karnowski** [comment]
Ah, this is what I get for verifying a bug on Stu's machine.  Come to find out, Stu was requiring jQuery twice.  This caused the $.print function to be unavailable.  I checked on my machine, and it's fine.
