### ISSUE TITLE
New gem version?

### ISSUE THREAD

**Issue by drnic** [relevance/blue-ridge#9]
Can we push out a new gem to include the jquery 1.3.2 headless patch etc?

**Comment by karnowski** [comment]
Nic, at this point Blue Ridge is only a Rails plugin.  Making it a gem is a goal, however.  For now you can just install the plugin from GitHub to get the jQuery 1.3.2 support.

**Comment by drnic** [comment]
You're right, I don't know why I thought there was a gem.
